# Generated by Django 5.0.6 on 2024-10-01 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qb', '0008_university_admission_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='university',
            name='name',
        ),
    ]
