# Generated by Django 5.0.6 on 2024-10-23 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Logo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Main', max_length=10, unique=True)),
                ('url', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='MainCopy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('copy', models.TextField()),
                ('url', models.TextField()),
            ],
        ),
    ]
