# Generated by Django 5.0.6 on 2024-10-23 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stuff', '0002_primaryimagecopy_alter_maincopy_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfilePictureURL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Profile Picture URLs',
            },
        ),
    ]
