# Generated by Django 5.0.6 on 2024-12-01 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stuff', '0005_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Name',
        ),
    ]
