# Generated by Django 5.0.6 on 2024-12-01 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stuff', '0006_delete_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Name',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pos', models.CharField(choices=[('Adjective', 'Adjective'), ('Noun', 'Noun')], max_length=10)),
                ('word', models.CharField(max_length=20, unique=True)),
            ],
        ),
    ]
