chapters = [
    "Parallelism & Redundancy",
    "Phrases & Idioms",
    "Pin Point Error",
    "Verb in Details",
    "Article",
    "Comprehension",
    "Pronoun",
    "One Word Substitution",
    "Right Form of Verb",
    "Subjunctive & Causative",
    "Analogy",
    "Number",
    "Tense & Sequence of Tense",
    "Conjunction & Linkers",
    "Miscellaneous",
    "Synonym & Antonym",
    "Sentence Correction",
    "Voice",
    "Degree of Comparison",
    "Translations & Proverbs",
    "WH Words & Embedded Questions",
    "Noun & Determiner",
    "Tag Question",
    "Adverb & Inversion",
    "Subject-Verb Agreement",
    "Gender",
    "Preposition",
    "Completing Sentence",
    "Narration",
    "Spelling",
    "Phrase & Clause in Details",
    "Dangling Modifier",
    "Literature",
    "Gerund Infinitive, Participle",
    "Group verb/ Phrasal verb",
    "Sentence & Its Transformations",
    "Parts of speech",
    "Adjective",
    "Conditional Sentence",
    "Affirmative & Negative Agreement"
]