# Generated by Django 5.0.6 on 2024-10-22 07:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0009_testanswer_participant_alter_test_marking_criterion_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='testtimer',
            old_name='start_time',
            new_name='start_datetime',
        ),
        migrations.AddField(
            model_name='testanswer',
            name='attempt',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='testanswer',
            name='participant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tests.testparticipant'),
        ),
        migrations.AddConstraint(
            model_name='testparticipant',
            constraint=models.UniqueConstraint(fields=('user', 'test'), name='duplicate_participant'),
        ),
    ]
