# Generated by Django 5.0.6 on 2024-10-22 22:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qb', '0009_remove_university_name'),
        ('tests', '0010_rename_start_time_testtimer_start_datetime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testparticipant',
            name='has_submitted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='testanswer',
            name='participant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='tests.testparticipant'),
        ),
        migrations.AddConstraint(
            model_name='testquestion',
            constraint=models.UniqueConstraint(fields=('test', 'question'), name='duplicate_question'),
        ),
    ]
