# Generated by Django 5.0.6 on 2024-10-23 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0011_testparticipant_has_submitted_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testanswer',
            old_name='attempt',
            new_name='attempted',
        ),
    ]
