# Generated by Django 5.0.6 on 2024-10-23 18:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qb', '0009_remove_university_name'),
        ('tests', '0012_rename_attempt_testanswer_attempted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testanswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qb.question'),
        ),
        migrations.DeleteModel(
            name='TestQuestion',
        ),
    ]
