# Generated by Django 5.0.6 on 2024-11-14 10:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0013_alter_testanswer_question_delete_testquestion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testparticipant',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='tests.test'),
        ),
    ]
